### ISSUE TITLE
Examples fail with UnsupportedOperationException

### ISSUE THREAD

**Issue by dakusui** [geophile/geophile#5]
Examples bundled with ```geophile``` do not work currently. Attached is a stacktrace given by ```PointsInBox``` demo.

This failure was apparently introduced in the commit ```6f4c402e284e4c405ad4109c000f7a4067d8f8b8``` pushed on 11/23/14.

Removing ```ExampleRecord#copyTo``` method (or reverting ```throw new UnsupportedOperationException()``` to the previous commit) suppresses this failure but judging from your following commit message, this wouldn't be a right solution.

> Added a distinction between indexes with stable and unstable records. A stable record, once retrieved from a cursor, never changes. An unstable record may change as a result of cursor operations. This can happen if the record derives its state from the current state of the cursor, for example. Stable records don't have to be copied (using Record.copyTo).  There is still one use of Record.copyTo, in some implementations of Index.add. Getting rid of this copy will require an API change.

### Attached

````
/usr/lib/jvm/java-7-oracle/bin/java -Didea.launcher.port=7536 -Didea.launcher.bin.path=/opt/idea-IC-162.1628.40/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-7-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-7-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-7-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-7-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jfxrt.jar:/usr/lib/jvm/java-7-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-7-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-7-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-7-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-7-oracle/jre/lib/rt.jar:/home/hiroshi/workspace/geophile/target/test-classes:/home/hiroshi/workspace/geophile/target/classes:/home/hiroshi/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar:/home/hiroshi/.m2/repository/com/vividsolutions/jts/1.13/jts-1.13.jar:/opt/idea-IC-162.1628.40/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain com.geophile.z.examples.PointsInBox
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.geophile.z.examples.ExampleRecord.copyTo(ExampleRecord.java:47)
	at com.geophile.z.index.tree.TreeIndex.add(TreeIndex.java:40)
	at com.geophile.z.space.SpatialIndexImpl.add(SpatialIndexImpl.java:41)
	at com.geophile.z.SpatialIndex.add(SpatialIndex.java:45)
	at com.geophile.z.examples.PointsInBox.run(PointsInBox.java:34)
	at com.geophile.z.examples.PointsInBox.main(PointsInBox.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
```

**Comment by geophile** [comment]
Hmm, very surprising. Thank you, Hiroshi, I will look into this in the next
couple of days.

**Comment by dakusui** [comment]
I see. I hope it helps.
And if you are going to use the pull request (#6), please share your code style file so that I can fix my pull request, whose style is broken by me.
